# Generated by Django 4.2.5 on 2023-10-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='indusfeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=50)),
                ('AboutIndustry', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='userfeed',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userfeed',
            name='Feedback',
            field=models.TextField(),
        ),
    ]
